#!/bin/bash
# https://docs.puppetlabs.com/guides/puppetlabs_package_repositories.html

path=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

pushd $path
/opt/puppetlabs/bin/puppet apply --modulepath=. site.pp
popd
